### ISSUE TITLE
Fix involucro

### ISSUE THREAD

**Issue by innovate-invent** [brinkmanlab/galaxy-container#7]
```
galaxy.jobs.runners.kubernetes DEBUG 2021-01-22 01:40:08,715 Starting queue_job for job 173121
galaxy.tool_util.deps.containers INFO 2021-01-22 01:40:09,008 Checking with container resolver [ExplicitContainerResolver[]] found description [None]
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
galaxy.tool_util.deps.container_resolvers.mulled INFO 2021-01-22 01:40:09,126 Call to `docker images` failed, configured container resolution may be broken
galaxy.tool_util.deps.containers INFO 2021-01-22 01:40:09,126 Checking with container resolver [CachedMulledDockerContainerResolver[namespace=biocontainers]] found description [None]
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
galaxy.tool_util.deps.container_resolvers.mulled INFO 2021-01-22 01:40:09,199 Call to `docker images` failed, configured container resolution may be broken
galaxy.tool_util.deps.containers INFO 2021-01-22 01:40:09,199 Checking with container resolver [CachedMulledDockerContainerResolver[namespace=local]] found description [None]
galaxy.tool_util.deps.containers INFO 2021-01-22 01:40:11,716 Checking with container resolver [MulledDockerContainerResolver[namespace=biocontainers]] found description [None]
galaxy.tool_util.deps.conda_util ERROR 2021-01-22 01:40:11,803 Could not execute: '['docker', 'run', 'continuumio/miniconda3:latest', 'conda', 'search', '--full-name', '--json', '--platform', 'linux-64', '--override-channels', '--channel', 'conda-forge', '--channel', 'bioconda', 'feature_merge']'
.
Executing: /srv/galaxy/involucro -v=3 -f /srv/galaxy/lib/galaxy/tool_util/deps/mulled/invfile.lua -set CHANNELS=conda-forge,bioconda -set TARGETS=feature_merge=1.3 -set REPO=quay.io/local/feature_merge:1.3 -set BINDS=build/dist:/usr/local/ -set DEST_BASE_IMAGE=bgruening/busybox-bash:0.1 -set TEST=true build-and-test
galaxy.tool_util.deps.containers ERROR 2021-01-22 01:40:11,804 Could not get container description for tool 'toolshed.g2.bx.psu.edu/repos/brinkmanlab/feature_merge/feature-merge/1.3'
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/tool_util/deps/containers.py", line 243, in find_best_container_description
    resolved_container_description = self.resolve(enabled_container_types, tool_info, **kwds)
  File "/srv/galaxy/lib/galaxy/tool_util/deps/containers.py", line 265, in resolve
    container_description = container_resolver.resolve(enabled_container_types, tool_info, install=install, resolution_cache=resolution_cache, session=session)
  File "/srv/galaxy/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 498, in resolve
    mull_targets(
  File "/srv/galaxy/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 286, in mull_targets
    ret = involucro_context.exec_command(involucro_args)
  File "/srv/galaxy/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 338, in exec_command
    os.mkdir('./build')
PermissionError: [Errno 13] Permission denied: './build'
galaxy.jobs.command_factory INFO 2021-01-22 01:40:11,893 Built script [/data/jobs_directory/000/173/173121/tool_script.sh] for tool command [feature_merge -v > /data/jobs_directory/000/173/173121/outputs/COMMAND_VERSION 2>&1; feature_merge -i   -m append -t 500 /data/database/files/000/240/dataset_240310.dat /data/database/files/000/240/dataset_240311.dat /data/database/files/000/240/dataset_240312.dat /data/database/files/000/240/dataset_240313.dat /data/database/files/000/240/dataset_240314.dat /data/database/files/000/240/dataset_240315.dat /data/database/files/000/240/dataset_240316.dat /data/database/files/000/240/dataset_240317.dat > /data/jobs_directory/000/173/173121/outputs/galaxy_dataset_9d7c66fe-8b1b-4fa1-9fda-ffceef935e1d.dat]
```

**Comment by innovate-invent** [comment]
Involucro should also be configured to push to a local registry deployment.
See #22 and https://github.com/brinkmanlab/cloud_recipes/issues/7
